### ISSUE TITLE
Producer error

### ISSUE THREAD

**Issue by yanivbh1** [memphisdev/memphis-broker#205]
<img width="781" alt="Screen Shot 2022-06-19 at 20 43 24" src="https://user-images.githubusercontent.com/70286779/174493773-289d5d48-c955-493f-ba89-b13f226498e4.png">

Sending 100000 messages to a 2-node memphis cluster receives a timeout after a certain point.
We need to check how to make an automatic throttling and notify the user for it

**Comment by idanasulinmemphis** [comment]
This issue happens because you are sending too many messages without waiting them to be published.
by awaiting a message to be produce you are sending the server an indication that you are still connected.
In case you don't want to wait to each message to be acked by the server, you can send bulk of messages and await them all together.
