### ISSUE TITLE
NATS

### ISSUE THREAD

**Issue by avin-kavish** [memphisdev/memphis-broker#222]
I was looking through the modules and noticed NATS. Isn't NATS by itself claiming to be a better queue to kafka, how does this library add to that?

**Comment by idanasulinmemphis** [comment]
Memphis is using NATS at its core for the basic functionality of an event streaming.
We forked NATS and put our own improvements on top of it. 
This fork will be integrated inside this repo in the next version. Until the integration with this repo will be completed the memphis-broker communicate with NATS(our fork version) via the SDK of NATS

**Comment by yanivbhemo** [comment]
Hey @avin-kavish,
Beside memphis improvements to NATS core, there is the entire ecosystem Memphis provides like UI/CLI, lightweight SDKs and in the coming releases - schema management, online processing, and gitops hub of ready-to-use connectors and components. Any more questions - please raise, we would love to help!

**Comment by avin-kavish** [comment]
great! And why did you choose mongo? High writes and scalability?

**Comment by idanasulinmemphis** [comment]
Ok so we took Mongo not for any special reason but for fast development in order to get the project up as fast as we can, in the coming versions we are going to remove it and not using a DB at all.
Just for clarifying, Mongo is in use for saving the application state and not the actual data producing into Memphis.
