### ISSUE TITLE
Clear poison messages counter per CG after ignore/ack

### ISSUE THREAD

**Issue by yanivbh1** [memphisdev/memphis-broker#242]
<img width="322" alt="Screen Shot 2022-07-19 at 14 47 16" src="https://user-images.githubusercontent.com/70286779/179742899-33be9137-060d-4de9-b497-705e6b40e871.png">

**Comment by AmreeshTyagi** [comment]
I was just testing DLQ & came to know that this issue still persist i.e. poisoned messages are not cleaned from DLQ evan after fixing consumer & acknowledging them.

I am assuming a situation when we have many thousand messages in DLQ & need to process them all in one go. 
Right now only 1000 messages can be processed at once, but it would be difficult if those are still in DLQ list view after processing.

I think poison counter is not the main problem here. Main problem may be the state of poison message in DLQ which is not changing & hence counter is same & messages are also visible in DLQ list. WDYT?

**Comment by idanasulinmemphis** [comment]
Hi @AmreeshTyagi, current behavior is indeed not best, after validating this feature with a lot of users I'm happy to share that we re-designed the DLQ behavior so that acking a message from an application will remove it from the DLQ. 
Not only this but also you will be able to consume the DLQ directly from your applications. 
Those features should be released on our near versions so stay tuned.

**Comment by AmreeshTyagi** [comment]
Thanks for the update. Sounds good. 👍🏻

**Comment by idanasulinmemphis** [comment]
This has been fixed in our latest version (0.4.2)
