### ISSUE TITLE
Benchmarking

### ISSUE THREAD

**Issue by yanivbh1** [memphisdev/memphis-broker#285]
## **Summary**
Create a benchmarking report in comparison to other brokers like Jetstream (NATS), Apache Kafka, Apache Pulsar, Redpanda

## **Context**
Raised by users. Increase trust, credibility, and a better understanding of Memphis's internal capabilities in terms of performance and throughput compared to other MQs/MBs.

## **Persona(s)**
- Data Engineers
- Developers
- DevOps
- New Users

**Comment by AmreeshTyagi** [comment]
Is there any update on this? I am hoping good results and want to use this MQ system instead of Kafka.

**Comment by valeraBr** [comment]
Hi @AmreeshTyagi ,

Thank you for getting in touch with me, we are working on an official document that will present our results. 
I can tell you that the results are already surprising and we will share them ASAP!
Meanwhile, you can try Memphis and see by yourself what I'm talking about, If you need any assistance we are here for you.

**Comment by AmreeshTyagi** [comment]
Thanks. Yes I have tried & still exploring it. Really easy to use compared to Kafka. 

Since it is based on NATS which support Pull based consumers as well, so I am 100% confident that it won't become throughput bottleneck like RabbitMQ as RabbitMQ is push based. Correct me please if I am assuming wrong.

Also waiting for throughput graphs on dashboard for consumer/producer. Hope those are also in plan somewhere.

**Comment by yanivbh1** [comment]
@AmreeshTyagi Thank you! That's great to read, as it's the main priority right now.
You are right + we have some advantages on vanilla NATS because we added the extra layer of consumer groups which allows you to scale the number of consumers in groups yet to preserve order.

Benchmarks will be out soon. @valeraBr from our team is on it.
